### ISSUE TITLE
Support reading binary data from an (unsigned-byte 8) vector

### ISSUE THREAD

**Issue by phmarek** [j3pic/lisp-binary#61]
The only way I could get data parsed from a `(unsigned-byte 8)` vector was this:

```lisp
    (flexi-streams:with-input-from-sequence (s1 ub8-vector)
      (lisp-binary:with-wrapped-in-bit-stream (s2 s1)
        (lisp-binary:read-binary 'dns-data s2)))))
```

Perhaps such vectors could be allowed directly in `READ-BINARY` instead of a `bit-stream`?

Thanks!

**Comment by j3pic** [comment]
It should be possible to use `with-input-from-sequence` without `with-wrapped-in-bit-stream`. Some of my unit tests do that without isssue. 

If I added a version of `read-binary` that was specialized on vectors instead of streams, it would just use `flexi-streams:with-input-from-sequence` and call the normal `read-binary`. This library consists of a ton of code that generates code to read data from streams. It wouldn't be practical to write versions of all the readers/writers that parse/fill a vector instead.

**Comment by phmarek** [comment]
Ack, thanks, will look at that.

**Comment by j3pic** [comment]
Reading my unit tests, it turns out I did this once:

```common-lisp
(defmethod read-bytes (n (stream sequence)
		       &rest options &key &allow-other-keys)
  (flexi-streams:with-input-from-sequence (in stream)
    (apply #'read-bytes (list* n in options))))
```

That worked because everything in the library uses that generic function instead of the built-in ones.

**Comment by j3pic** [comment]
It doesn't work with bit-stream stuff, though: Some of the Gray stream functions use `read-byte` directly.
